services:
  # postgres:
  #   image: postgres:16-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: atendio
  #   ports:
  #     - "5438:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:6
  #   ports:
  #     - "6381:6379"
  #   volumes:
  #     - redis_data:/var/lib/redis/data

  app:
    build: .
    ports:
      - "5100:5000"
    env_file:
      - .env.docker
    volumes:
      - uploads:/app/uploads

volumes:
  # postgres_data:
  # redis_data:
  uploads:
